Configuration cUpdateServicesFeatures {
	WindowsFeature FileAndStorage-Services { Name = 'FileAndStorage-Services'; Ensure = 'Present' }
	WindowsFeature File-Services { Name = 'File-Services'; Ensure = 'Present' }
	WindowsFeature FS-FileServer { Name = 'FS-FileServer'; Ensure = 'Present' }
	WindowsFeature Storage-Services { Name = 'Storage-Services'; Ensure = 'Present' }
	WindowsFeature Web-Server { Name = 'Web-Server'; Ensure = 'Present' }
	WindowsFeature Web-WebServer { Name = 'Web-WebServer'; Ensure = 'Present' }
	WindowsFeature Web-Common-Http { Name = 'Web-Common-Http'; Ensure = 'Present' }
	WindowsFeature Web-Default-Doc { Name = 'Web-Default-Doc'; Ensure = 'Present' }
	WindowsFeature Web-Dir-Browsing { Name = 'Web-Dir-Browsing'; Ensure = 'Present' }
	WindowsFeature Web-Http-Errors { Name = 'Web-Http-Errors'; Ensure = 'Present' }
	WindowsFeature Web-Static-Content { Name = 'Web-Static-Content'; Ensure = 'Present' }
	WindowsFeature Web-Health { Name = 'Web-Health'; Ensure = 'Present' }
	WindowsFeature Web-Http-Logging { Name = 'Web-Http-Logging'; Ensure = 'Present' }
	WindowsFeature Web-Request-Monitor { Name = 'Web-Request-Monitor'; Ensure = 'Present' }
	WindowsFeature Web-Http-Tracing { Name = 'Web-Http-Tracing'; Ensure = 'Present' }
	WindowsFeature Web-Performance { Name = 'Web-Performance'; Ensure = 'Present' }
	WindowsFeature Web-Stat-Compression { Name = 'Web-Stat-Compression'; Ensure = 'Present' }
	WindowsFeature Web-Dyn-Compression { Name = 'Web-Dyn-Compression'; Ensure = 'Present' }
	WindowsFeature Web-Security { Name = 'Web-Security'; Ensure = 'Present' }
	WindowsFeature Web-Filtering { Name = 'Web-Filtering'; Ensure = 'Present' }
	WindowsFeature Web-Windows-Auth { Name = 'Web-Windows-Auth'; Ensure = 'Present' }
	WindowsFeature Web-App-Dev { Name = 'Web-App-Dev'; Ensure = 'Present' }
	WindowsFeature Web-Net-Ext45 { Name = 'Web-Net-Ext45'; Ensure = 'Present' }
	WindowsFeature Web-Asp-Net45 { Name = 'Web-Asp-Net45'; Ensure = 'Present' }
	WindowsFeature Web-ISAPI-Ext { Name = 'Web-ISAPI-Ext'; Ensure = 'Present' }
	WindowsFeature Web-ISAPI-Filter { Name = 'Web-ISAPI-Filter'; Ensure = 'Present' }
	WindowsFeature Web-Mgmt-Tools { Name = 'Web-Mgmt-Tools'; Ensure = 'Present' }
	WindowsFeature Web-Mgmt-Console { Name = 'Web-Mgmt-Console'; Ensure = 'Present' }
	WindowsFeature Web-Mgmt-Compat { Name = 'Web-Mgmt-Compat'; Ensure = 'Present' }
	WindowsFeature Web-Metabase { Name = 'Web-Metabase'; Ensure = 'Present' }
	WindowsFeature UpdateServices { Name = 'UpdateServices'; Ensure = 'Present' }
	WindowsFeature UpdateServices-WidDB { Name = 'UpdateServices-WidDB'; Ensure = 'Present' }
	WindowsFeature UpdateServices-Services { Name = 'UpdateServices-Services'; Ensure = 'Present' }
	WindowsFeature NET-Framework-45-Features { Name = 'NET-Framework-45-Features'; Ensure = 'Present' }
	WindowsFeature NET-Framework-45-Core { Name = 'NET-Framework-45-Core'; Ensure = 'Present' }
	WindowsFeature NET-Framework-45-ASPNET { Name = 'NET-Framework-45-ASPNET'; Ensure = 'Present' }
	WindowsFeature NET-WCF-Services45 { Name = 'NET-WCF-Services45'; Ensure = 'Present' }
	WindowsFeature NET-WCF-HTTP-Activation45 { Name = 'NET-WCF-HTTP-Activation45'; Ensure = 'Present' }
	WindowsFeature NET-WCF-TCP-PortSharing45 { Name = 'NET-WCF-TCP-PortSharing45'; Ensure = 'Present' }
	WindowsFeature ManagementOdata { Name = 'ManagementOdata'; Ensure = 'Present' }
	WindowsFeature RSAT { Name = 'RSAT'; Ensure = 'Present' }
	WindowsFeature RSAT-Role-Tools { Name = 'RSAT-Role-Tools'; Ensure = 'Present' }
	WindowsFeature UpdateServices-RSAT { Name = 'UpdateServices-RSAT'; Ensure = 'Present' }
	WindowsFeature UpdateServices-API { Name = 'UpdateServices-API'; Ensure = 'Present' }
	WindowsFeature UpdateServices-UI { Name = 'UpdateServices-UI'; Ensure = 'Present' }
	WindowsFeature FS-SMB1 { Name = 'FS-SMB1'; Ensure = 'Present' }
	WindowsFeature User-Interfaces-Infra { Name = 'User-Interfaces-Infra'; Ensure = 'Present' }
	WindowsFeature Server-Gui-Mgmt-Infra { Name = 'Server-Gui-Mgmt-Infra'; Ensure = 'Present' }
	WindowsFeature Server-Gui-Shell { Name = 'Server-Gui-Shell'; Ensure = 'Present' }
	WindowsFeature Windows-Internal-Database { Name = 'Windows-Internal-Database'; Ensure = 'Present' }
	WindowsFeature PowerShellRoot { Name = 'PowerShellRoot'; Ensure = 'Present' }
	WindowsFeature PowerShell { Name = 'PowerShell'; Ensure = 'Present' }
	WindowsFeature DSC-Service { Name = 'DSC-Service'; Ensure = 'Present' }
	WindowsFeature PowerShell-ISE { Name = 'PowerShell-ISE'; Ensure = 'Present' }
	WindowsFeature WAS { Name = 'WAS'; Ensure = 'Present' }
	WindowsFeature WAS-Process-Model { Name = 'WAS-Process-Model'; Ensure = 'Present' }
	WindowsFeature WAS-Config-APIs { Name = 'WAS-Config-APIs'; Ensure = 'Present' }
	WindowsFeature WoW64-Support { Name = 'WoW64-Support'; Ensure = 'Present' }
}
